### ISSUE TITLE
Error: `.predicate` has no matching columns

### ISSUE THREAD

**Issue by jaliasd** [USAID-OHA-SI/asSIMSble#2]
#install devtools
`install.packages("devtools")

#install/update package
devtools::install_github("USAID-OHA-SI/asSIMSble")
#load package
library("asSIMSble")

#parameters - adjust to reflext location on your machine
  filepath <- "C:/Users/GHFP/Documents/data/11_15_release/site_level"
  template_filepath <- "C:/Users/GHFP/Documents/data/11_15_release/asSIMSble/Products/sims_prioritization_template.xlsx"
  output_folderpath <- "C:/Users/GHFP/Documents/data/11_15_release/asSIMSble/Products"
  

  files <- dir(filepath, pattern = "*.rds", full.names = TRUE)
  
  
  #list files
  files <- dir(filepath, pattern = "*.rds", full.names = TRUE)
  

  #process multiple template creations
  map(.x = files,
      .f = ~ assemble(.x, template_filepath, output_folderpath))
  `

Gives this error. I think from the debug it looks like ` -dplyr::summarise_at(., dplyr::vars(fy2018cum), ~sum(., na.rm = TRUE))
`
is looking for fy2018cum, which isn't there anymore. Should it be fy2018apr?

![image](https://user-images.githubusercontent.com/8836685/49331303-cbd5f200-f568-11e8-897f-bc1cbdd7fa66.png)

**Comment by achafetz** [comment]
Unfortunately, the very first country you ran (Angola) is missing OVC_SERV/OVC_HIVSTATUS.  The script threw up an error since it first filtered for those two variables (both missing) and then tried to munge on an empty dataframe --> ERROR

https://github.com/USAID-OHA-SI/asSIMSble/blob/0d4ee47a4e84bf875076152d1201ec25892d50cf/R/score_stat.r#L13-L16

The solution was to add in `if` statements to skip over the calculations if either were missing. I added in another for PMTCT_STAT and TB_STAT (skip if both were missing).

There shouldn't be an issue with the other indicators since they are HTS_TST and TX_NEW, which every country will have. And the performance indicators should also be okay because there will be at the very least HTS_TST and TX_NEW.

Fingers crossed this should be the only error you get. :crossed_fingers:
